[package]
name = "guardian"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "guardian"
path = "./src/main.rs"

[dependencies]
# Async dep
tokio = {version = "1", features = ["full"]}
futures = "0.3"
tracing = "~0.1"
tracing-subscriber = "~0.3"
# User deps
uuid = {version = "1.2", features = ["v4"]}
# Oher deps
chrono = "0.4"
parking_lot = "0.12"
# Web deps
actix-web = { version = "~4.6", features = ["rustls-0_22", "cookies"] }
actix-web-httpauth = "0.8"
# Auth deps
argon2 = { version = "0.5", features = ["std"] }
rand_core = { version = "0.6", features = ["std"] }
sha2 = "~0.10"
jsonwebtoken = { version = "9.0.0", features = ["use_pem"] }
openssl = "~0.10"
tokio-rustls = "0.26"
rustls = "0.23"
rustls-pemfile = "2.0"
rustls-pki-types = "1.0.1"
# Serialization
serde = { version = "~1.0", features = ["derive"] }
serde_json = "~1.0.81"
# DB
redis = { version = "0.25", features = ["tokio-comp"] }

[profile.dev]
opt-level = 0
debug = 2
overflow-checks = true
lto = false
[profile.release]
opt-level = 3
overflow-checks = false
lto = true
