[openid-w3]
url = "https://preprod.login.w3.ibm.com/oidc/endpoint/default"
redirect_url = "https://ae814485de68d45a7b81b063be9ca78f-2001013949.us-east-2.elb.amazonaws.com:8080/auth/redirect"
# redirect_url = "https://localhost:8080/auth/redirect"

	[openid-w3.client]
	client_id = ""
	client_secret = ""

[openid-ibmid]
url = "https://prepiam.ice.ibmcloud.com/oidc/endpoint/default"
redirect_url = "https://ae814485de68d45a7b81b063be9ca78f-2001013949.us-east-2.elb.amazonaws.com:8080/auth/callback"
# redirect_url = "https://localhost:8080/auth/callback"

	[openid-ibmid.client]
	client_id = ""
	client_secret = ""
