[openwebui]
namespace = "openwebui"
service_port = 8080
url = "oweb.open.accelerate.science"

[openwebui.image]
registry = "quay.io"
repository = "ibmdpdev/open-webui-spati"
tag = "latest"
pull_policy = "Always"
image_pull_secret = "ecr-registry-secret"

[openwebui.alt_image]
registry = "866335085214.dkr.ecr.us-east-1.amazonaws.com"
repository = "openwebuis"
image_pull_secret = "ecr-registry-secret"

[openwebui.persistence]
size = "10Gi"
storage_class = "gp3"

[[openwebui.env]]
MOLVIEWER_URL = "moleviewer.open.accelerate.science"
[[openwebui.env]]
WEBUI_SECRET_KEY = "idontcarewhatthisisbecuasethisisrequiredforsomereason"
