[services]

	[services.postman]
	url = "https://postman-echo.com"
	readiness = "/get"
	check = true
	mcp = false
	description = "Postman echo server for testing purposes"

	[services.postman-mcp]
	url = "https://postman-echo.com"
	readiness = "/get"
	check = true
	mcp = true
	description = "Postman echo server for mcp testing purposes"

	# Not a service with a readiness check, see services.rs for more details
	[services.notebook]
	url = ""
	readiness = ""
	check = false
	mcp = false

	# This is a supplementary entry to notebook for heavier resource
	[services.notebook_heavy]
	url = ""
	readiness = ""
	check = false
	mcp = false

	[services.owui]
	url = ""
	readiness = ""
	check = false
	mcp = false

[resources]

	[resources.example]
	url = "https://www.example.com"
	readiness = "/"
	check = true
	show = true
	description = "Example.com for testing purposes"

	[resources.reddit]
	url = "https://www.reddit.com"
	readiness = "/"
	check = true
	show = false
	description = "Reddit.com for testing purposes. This is a much longer text description. Blah blah blah blah. Also this resource should not show up in the side menu."
	[resources.main-api]
	url = "http://main-api.chemchat.svc.cluster.local:8000"
	readiness = "/health"
	check = true
	show = false

	[resources.chemchat]
	url = "http://frontend.chemchat.svc.cluster.local:5173"
	readiness = "/health"
	check = true
	show = true

	[resources.cheminfo-services]
	url = "http://cheminfo-services.chemchat.svc.cluster.local:8000"
	readiness = "/health"
	check = true
	show = false
