[services]

	[services.postman]
	url = "https://postman-echo.com"
	readiness = "/get"
	check = true
	mcp = false

	[services.postman-mcp]
	url = "https://postman-echo.com"
	readiness = "/get"
	check = true
	mcp = true

	# Not a service with a readiness check, see services.rs for more details
	[services.notebook]
	url = ""
	readiness = ""
	check = false
	mcp = false

	[services.owui]
	url = ""
	readiness = ""
	check = false
	mcp = false

[resources]

	[resources.example]
	url = "https://www.example.com"
	readiness = "/"
	check = true
	show = true

	[resources.reddit]
	url = "https://www.reddit.com"
	readiness = "/"
	check = true
	show = false
