[services]

	[services.postman]
	url = "https://postman-echo.com"
	readiness = "/get"
	check = true

	[services.properties]
	url = "http://property-inference-service.openad-models.svc.cluster.local"
	readiness = "/health"
	check = true

	[services.generation]
	url = "http://generation-inference-service.openad-models.svc.cluster.local"
	readiness = "/health"
	check = true

	[services.molformer]
	url = "http://molformer-inference-service.openad-models.svc.cluster.local"
	readiness = "/health"
	check = true

	[services.moler]
	url = "http://moler-inference-service.openad-models.svc.cluster.local"
	readiness = "/health"
	check = true

	[services.bmfm]
	url = "http://bmfm-inference-service.openad-models.svc.cluster.local"
	readiness = "/health"
	check = true

	[services.bmfm-small-molecules]
	url = "http://sm-bmfm-sm-inference.openad-models.svc.cluster.local"
	readiness = "/health"
	check = true

	[services.bmfm-mammal]
	url = "http://mammal-bmfm-mammal-inference.openad-models.svc.cluster.local"
	readiness = "/health"
	check = true

	[services.pfas]
	url = "http://pfas-openad-model.openad-models.svc.cluster.local"
	readiness = "/health"
	check = true
	
	[services.smi-ted]
	url = "http://smi-ted-openad-model.openad-models.svc.cluster.local"
	readiness = "/health"
	check = true

	# Not a service with a readiness check, see services.rs for more details
	[services.notebook]
	url = ""
	readiness = ""
	check = false
