[services]

	[services.postman]
	url = "https://postman-echo.com"
	readiness = "/get"
	check = true
	mcp = false
	description = "Postman echo server for testing purposes"

	[services.postman-mcp]
	url = "https://postman-echo.com"
	readiness = "/get"
	check = true
	mcp = true
	description = "Postman echo server for mcp testing purposes"

	# Not a service with a readiness check, see services.rs for more details
	[services.notebook]
	url = ""
	readiness = ""
	check = false
	mcp = false

	# This is a supplementary entry to notebook for heavier resource
	[services.notebook_heavy]
	url = ""
	readiness = ""
	check = false
	mcp = false

	[services.owui]
	url = ""
	readiness = ""
	check = false
	mcp = false

[resources]

	[resources.example]
	url = "https://www.example.com"
	readiness = "/"
	check = true
	show = true
	description = "Example.com for testing purposes"

	[resources.reddit]
	url = "https://www.reddit.com"
	readiness = "/"
	check = true
	show = false
